#############################################################################
# Makefile for building: diplomaDB.app/Contents/MacOS/diplomaDB
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  diplomaDB.pro
# Template: app
# Command: /Users/andrii/Qt/6.4.2/macos/bin/qmake -o Makefile diplomaDB.pro -spec macx-clang CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers -I../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers -I../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers -I../../Qt/6.4.2/macos/lib/QtGui.framework/Headers -I../../Qt/6.4.2/macos/lib/QtNetwork.framework/Headers -I../../Qt/6.4.2/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/6.4.2/macos/mkspecs/macx-clang -F/Users/andrii/Qt/6.4.2/macos/lib
QMAKE         = /Users/andrii/Qt/6.4.2/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/andrii/Qt/6.4.2/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/andrii/Qt/6.4.2/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = diplomaDB1.0.0
DISTDIR = /Users/andrii/Desktop/diplomaDB/.tmp/diplomaDB1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/andrii/Qt/6.4.2/macos/lib
LIBS          = $(SUBLIBS) -F/Users/andrii/Qt/6.4.2/macos/lib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtNetwork -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		preloader.cpp qrc_recources.cpp \
		moc_mainwindow.cpp \
		moc_preloader.cpp
OBJECTS       = main.o \
		mainwindow.o \
		preloader.o \
		qrc_recources.o \
		moc_mainwindow.o \
		moc_preloader.o
DIST          = ../../Qt/6.4.2/macos/mkspecs/features/spec_pre.prf \
		../../Qt/6.4.2/macos/mkspecs/features/device_config.prf \
		../../Qt/6.4.2/macos/mkspecs/common/unix.conf \
		../../Qt/6.4.2/macos/mkspecs/common/mac.conf \
		../../Qt/6.4.2/macos/mkspecs/common/macx.conf \
		../../Qt/6.4.2/macos/mkspecs/common/sanitize.conf \
		../../Qt/6.4.2/macos/mkspecs/common/gcc-base.conf \
		../../Qt/6.4.2/macos/mkspecs/common/gcc-base-mac.conf \
		../../Qt/6.4.2/macos/mkspecs/common/clang.conf \
		../../Qt/6.4.2/macos/mkspecs/common/clang-mac.conf \
		../../Qt/6.4.2/macos/mkspecs/qconfig.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/features/qt_functions.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qt_config.prf \
		../../Qt/6.4.2/macos/mkspecs/macx-clang/qmake.conf \
		../../Qt/6.4.2/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.4.2/macos/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/sdk.prf \
		../../Qt/6.4.2/macos/mkspecs/features/toolchain.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/toolchain.prf \
		../../Qt/6.4.2/macos/mkspecs/features/default_pre.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/default_pre.prf \
		../../Qt/6.4.2/macos/mkspecs/features/resolve_config.prf \
		../../Qt/6.4.2/macos/mkspecs/features/default_post.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/default_post.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/objective_c.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qtquickcompiler.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/mac.prf \
		../../Qt/6.4.2/macos/mkspecs/features/warn_on.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qt.prf \
		../../Qt/6.4.2/macos/mkspecs/features/resources_functions.prf \
		../../Qt/6.4.2/macos/mkspecs/features/resources.prf \
		../../Qt/6.4.2/macos/mkspecs/features/moc.prf \
		../../Qt/6.4.2/macos/mkspecs/features/unix/opengl.prf \
		../../Qt/6.4.2/macos/mkspecs/features/uic.prf \
		../../Qt/6.4.2/macos/mkspecs/features/unix/thread.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qmake_use.prf \
		../../Qt/6.4.2/macos/mkspecs/features/file_copies.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/rez.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/6.4.2/macos/mkspecs/features/testcase_targets.prf \
		../../Qt/6.4.2/macos/mkspecs/features/exceptions.prf \
		../../Qt/6.4.2/macos/mkspecs/features/yacc.prf \
		../../Qt/6.4.2/macos/mkspecs/features/lex.prf \
		diplomaDB.pro mainwindow.h \
		preloader.h main.cpp \
		mainwindow.cpp \
		preloader.cpp
QMAKE_TARGET  = diplomaDB
DESTDIR       = 
TARGET        = diplomaDB.app/Contents/MacOS/diplomaDB

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/andrii/Desktop/diplomaDB/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/andrii/Desktop/diplomaDB/diplomaDB.pro


include /Users/andrii/Qt/6.4.2/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

diplomaDB.app/Contents/MacOS/diplomaDB: ui_mainwindow.h ui_preloader.h $(OBJECTS)  
	@test -d diplomaDB.app/Contents/MacOS/ || mkdir -p diplomaDB.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: diplomaDB.pro ../../Qt/6.4.2/macos/mkspecs/macx-clang/qmake.conf ../../Qt/6.4.2/macos/mkspecs/features/spec_pre.prf \
		../../Qt/6.4.2/macos/mkspecs/features/device_config.prf \
		../../Qt/6.4.2/macos/mkspecs/common/unix.conf \
		../../Qt/6.4.2/macos/mkspecs/common/mac.conf \
		../../Qt/6.4.2/macos/mkspecs/common/macx.conf \
		../../Qt/6.4.2/macos/mkspecs/common/sanitize.conf \
		../../Qt/6.4.2/macos/mkspecs/common/gcc-base.conf \
		../../Qt/6.4.2/macos/mkspecs/common/gcc-base-mac.conf \
		../../Qt/6.4.2/macos/mkspecs/common/clang.conf \
		../../Qt/6.4.2/macos/mkspecs/common/clang-mac.conf \
		../../Qt/6.4.2/macos/mkspecs/qconfig.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.4.2/macos/mkspecs/features/qt_functions.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qt_config.prf \
		../../Qt/6.4.2/macos/mkspecs/macx-clang/qmake.conf \
		../../Qt/6.4.2/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.4.2/macos/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/sdk.prf \
		../../Qt/6.4.2/macos/mkspecs/features/toolchain.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/toolchain.prf \
		../../Qt/6.4.2/macos/mkspecs/features/default_pre.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/default_pre.prf \
		../../Qt/6.4.2/macos/mkspecs/features/resolve_config.prf \
		../../Qt/6.4.2/macos/mkspecs/features/default_post.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/default_post.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/objective_c.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qtquickcompiler.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/mac.prf \
		../../Qt/6.4.2/macos/mkspecs/features/warn_on.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qt.prf \
		../../Qt/6.4.2/macos/mkspecs/features/resources_functions.prf \
		../../Qt/6.4.2/macos/mkspecs/features/resources.prf \
		../../Qt/6.4.2/macos/mkspecs/features/moc.prf \
		../../Qt/6.4.2/macos/mkspecs/features/unix/opengl.prf \
		../../Qt/6.4.2/macos/mkspecs/features/uic.prf \
		../../Qt/6.4.2/macos/mkspecs/features/unix/thread.prf \
		../../Qt/6.4.2/macos/mkspecs/features/qmake_use.prf \
		../../Qt/6.4.2/macos/mkspecs/features/file_copies.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/rez.prf \
		../../Qt/6.4.2/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/6.4.2/macos/mkspecs/features/testcase_targets.prf \
		../../Qt/6.4.2/macos/mkspecs/features/exceptions.prf \
		../../Qt/6.4.2/macos/mkspecs/features/yacc.prf \
		../../Qt/6.4.2/macos/mkspecs/features/lex.prf \
		diplomaDB.pro \
		recources.qrc \
		../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Resources/QtMultimediaWidgets.prl \
		../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Resources/QtMultimedia.prl \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../Qt/6.4.2/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../Qt/6.4.2/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile diplomaDB.pro -spec macx-clang CONFIG+=qtquickcompiler
../../Qt/6.4.2/macos/mkspecs/features/spec_pre.prf:
../../Qt/6.4.2/macos/mkspecs/features/device_config.prf:
../../Qt/6.4.2/macos/mkspecs/common/unix.conf:
../../Qt/6.4.2/macos/mkspecs/common/mac.conf:
../../Qt/6.4.2/macos/mkspecs/common/macx.conf:
../../Qt/6.4.2/macos/mkspecs/common/sanitize.conf:
../../Qt/6.4.2/macos/mkspecs/common/gcc-base.conf:
../../Qt/6.4.2/macos/mkspecs/common/gcc-base-mac.conf:
../../Qt/6.4.2/macos/mkspecs/common/clang.conf:
../../Qt/6.4.2/macos/mkspecs/common/clang-mac.conf:
../../Qt/6.4.2/macos/mkspecs/qconfig.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_freetype.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_ext_libpng.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_charts.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core5compat.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designer.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_gui.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_help.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_httpserver.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_httpserver_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_languageserver_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_linguist.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_network.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdf.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdf_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfquick.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_png_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysics.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_shadertools.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sql.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachine.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svg.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequick.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webview.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webviewquick.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_xml.pri:
../../Qt/6.4.2/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/6.4.2/macos/mkspecs/features/qt_functions.prf:
../../Qt/6.4.2/macos/mkspecs/features/qt_config.prf:
../../Qt/6.4.2/macos/mkspecs/macx-clang/qmake.conf:
../../Qt/6.4.2/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/6.4.2/macos/mkspecs/features/exclusive_builds.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/sdk.prf:
../../Qt/6.4.2/macos/mkspecs/features/toolchain.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/toolchain.prf:
../../Qt/6.4.2/macos/mkspecs/features/default_pre.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/default_pre.prf:
../../Qt/6.4.2/macos/mkspecs/features/resolve_config.prf:
../../Qt/6.4.2/macos/mkspecs/features/default_post.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/default_post.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/objective_c.prf:
../../Qt/6.4.2/macos/mkspecs/features/qtquickcompiler.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/mac.prf:
../../Qt/6.4.2/macos/mkspecs/features/warn_on.prf:
../../Qt/6.4.2/macos/mkspecs/features/qt.prf:
../../Qt/6.4.2/macos/mkspecs/features/resources_functions.prf:
../../Qt/6.4.2/macos/mkspecs/features/resources.prf:
../../Qt/6.4.2/macos/mkspecs/features/moc.prf:
../../Qt/6.4.2/macos/mkspecs/features/unix/opengl.prf:
../../Qt/6.4.2/macos/mkspecs/features/uic.prf:
../../Qt/6.4.2/macos/mkspecs/features/unix/thread.prf:
../../Qt/6.4.2/macos/mkspecs/features/qmake_use.prf:
../../Qt/6.4.2/macos/mkspecs/features/file_copies.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/rez.prf:
../../Qt/6.4.2/macos/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/6.4.2/macos/mkspecs/features/testcase_targets.prf:
../../Qt/6.4.2/macos/mkspecs/features/exceptions.prf:
../../Qt/6.4.2/macos/mkspecs/features/yacc.prf:
../../Qt/6.4.2/macos/mkspecs/features/lex.prf:
diplomaDB.pro:
recources.qrc:
../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Resources/QtMultimediaWidgets.prl:
../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Resources/QtMultimedia.prl:
../../Qt/6.4.2/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../Qt/6.4.2/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../Qt/6.4.2/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../Qt/6.4.2/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile diplomaDB.pro -spec macx-clang CONFIG+=qtquickcompiler

qmake_all: FORCE

diplomaDB.app/Contents/PkgInfo: 
	@test -d diplomaDB.app/Contents || mkdir -p diplomaDB.app/Contents
	@$(DEL_FILE) diplomaDB.app/Contents/PkgInfo
	@echo "APPL????" > diplomaDB.app/Contents/PkgInfo
diplomaDB.app/Contents/Resources/empty.lproj: 
	@test -d diplomaDB.app/Contents/Resources || mkdir -p diplomaDB.app/Contents/Resources
	@touch diplomaDB.app/Contents/Resources/empty.lproj
	
diplomaDB.app/Contents/Info.plist: 
	@test -d diplomaDB.app/Contents || mkdir -p diplomaDB.app/Contents
	@$(DEL_FILE) diplomaDB.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,bj.diplomaDB,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},bj.diplomaDB,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,AppIcon.icns,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},AppIcon.icns,g" -e "s,@EXECUTABLE@,diplomaDB,g" -e "s,@LIBRARY@,diplomaDB,g" -e "s,\$${EXECUTABLE_NAME},diplomaDB,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt/6.4.2/macos/mkspecs/macx-clang/Info.plist.app >diplomaDB.app/Contents/Info.plist
diplomaDB.app/Contents/Resources/AppIcon.icns: img/AppIcon.icns
	@test -d diplomaDB.app/Contents/Resources/ || mkdir -p diplomaDB.app/Contents/Resources/
	@$(DEL_FILE) diplomaDB.app/Contents/Resources/AppIcon.icns
	@$(COPY_FILE) img/AppIcon.icns diplomaDB.app/Contents/Resources/AppIcon.icns

all: Makefile \
		diplomaDB.app/Contents/PkgInfo \
		diplomaDB.app/Contents/Resources/empty.lproj \
		diplomaDB.app/Contents/Info.plist \
		diplomaDB.app/Contents/Resources/AppIcon.icns diplomaDB.app/Contents/MacOS/diplomaDB

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents recources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h preloader.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp preloader.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui preloader.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r diplomaDB.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=qtquickcompiler

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_recources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_recources.cpp
qrc_recources.cpp: recources.qrc \
		../../Qt/6.4.2/macos/libexec/rcc \
		img/2.png \
		img/3.png \
		img/1.png \
		img/preloader.mp4 \
		img/AppIcon.icns \
		img/mainLogo/mainIcox510.png \
		img/mainLogo/mainIcox128.png \
		img/mainLogo/mainIcox64.png \
		img/whiteMenuIcon/settinfIco.png \
		img/pinkMenuicon/settinfIco.png
	/Users/andrii/Qt/6.4.2/macos/libexec/rcc -name recources --no-zstd recources.qrc -o qrc_recources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_preloader.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_preloader.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QString \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QEvent \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/6.4.2/macos/libexec/moc
	/Users/andrii/Qt/6.4.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/andrii/Qt/6.4.2/macos/mkspecs/macx-clang -I/Users/andrii/Desktop/diplomaDB -I/Users/andrii/Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtWidgets.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtGui.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtNetwork.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/andrii/Qt/6.4.2/macos/lib mainwindow.h -o moc_mainwindow.cpp

moc_preloader.cpp: preloader.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		mainwindow.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QString \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QEvent \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/6.4.2/macos/libexec/moc
	/Users/andrii/Qt/6.4.2/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/andrii/Qt/6.4.2/macos/mkspecs/macx-clang -I/Users/andrii/Desktop/diplomaDB -I/Users/andrii/Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtWidgets.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtGui.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtNetwork.framework/Headers -I/Users/andrii/Qt/6.4.2/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/andrii/Qt/6.4.2/macos/lib preloader.h -o moc_preloader.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_preloader.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_preloader.h
ui_mainwindow.h: mainwindow.ui \
		../../Qt/6.4.2/macos/libexec/uic
	/Users/andrii/Qt/6.4.2/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

ui_preloader.h: preloader.ui \
		../../Qt/6.4.2/macos/libexec/uic
	/Users/andrii/Qt/6.4.2/macos/libexec/uic preloader.ui -o ui_preloader.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp preloader.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		mainwindow.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QString \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QEvent \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qcoreevent.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QString \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QEvent \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qcoreevent.h \
		ui_mainwindow.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

preloader.o: preloader.cpp preloader.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers/QVideoWidget \
		../../Qt/6.4.2/macos/lib/QtMultimediaWidgets.framework/Headers/qvideowidget.h \
		../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../Qt/6.4.2/macos/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		mainwindow.h \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt/6.4.2/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QString \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/QEvent \
		../../Qt/6.4.2/macos/lib/QtCore.framework/Headers/qcoreevent.h \
		ui_preloader.h \
		../../Qt/6.4.2/macos/lib/QtGui.framework/Headers/QPainterPath \
		../../Qt/6.4.2/macos/lib/QtGui.framework/Headers/qpainterpath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preloader.o preloader.cpp

qrc_recources.o: qrc_recources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_recources.o qrc_recources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_preloader.o: moc_preloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preloader.o moc_preloader.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/diplomaDB/bin || mkdir -p $(INSTALL_ROOT)/opt/diplomaDB/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/diplomaDB/bin/diplomaDB.app
	
	$(QINSTALL) diplomaDB.app $(INSTALL_ROOT)/opt/diplomaDB/bin/diplomaDB.app
	-$(STRIP) $(INSTALL_ROOT)/opt/diplomaDB/bin/diplomaDB.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/diplomaDB/bin/diplomaDB.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/diplomaDB/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

